name: CI

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Setup tools
        uses: jdx/mise-action@c1606014a9b1b7cd3e7c7f5fc607a25351fdffec # v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run formatter, linter and import sorting with Biome
        run: bun run biome ci .

  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Setup tools
        uses: jdx/mise-action@c1606014a9b1b7cd3e7c7f5fc607a25351fdffec # v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run formatter, linter and import sorting with Biome
        run: bun run test:coverage

  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Setup tools
        uses: jdx/mise-action@c1606014a9b1b7cd3e7c7f5fc607a25351fdffec # v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build
        run: bun run build
