name: CI

on:
  push:
  pull_request:
    branches:
      - main
  merge_group:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        working-directory:
          - .
          - templates/bun-npm-package
          - templates/slidev
    defaults:
      run:
        working-directory: ${{ matrix.working-directory }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Setup Bun and Node.js
        uses: jdx/mise-action@c1606014a9b1b7cd3e7c7f5fc607a25351fdffec # v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Check
        run: bun run check:ci

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        working-directory:
          - .
          - templates/bun-npm-package
          - templates/slidev
    defaults:
      run:
        working-directory: ${{ matrix.working-directory }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Setup Bun and Node.js
        uses: jdx/mise-action@c1606014a9b1b7cd3e7c7f5fc607a25351fdffec # v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build
        run: bun run build

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        working-directory:
          - .
          - templates/bun-npm-package
          - templates/slidev
    defaults:
      run:
        working-directory: ${{ matrix.working-directory }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Setup Bun and Node.js
        uses: jdx/mise-action@c1606014a9b1b7cd3e7c7f5fc607a25351fdffec # v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Test
        run: bun run test
