name: CI

on:
  push:
  pull_request:
    branches:
      - main
  merge_group:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        working-directory:
          - .
          - templates/bun-npm-package
          - templates/slidev
    defaults:
      run:
        working-directory: ${{ matrix.working-directory }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup Bun and Node.js
        uses: jdx/mise-action@d6e32c1796099e0f1f3ac741c220a8b7eae9e5dd # v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Check
        run: bun run check:ci

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        working-directory:
          - .
          - templates/bun-npm-package
          - templates/slidev
    defaults:
      run:
        working-directory: ${{ matrix.working-directory }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup Bun and Node.js
        uses: jdx/mise-action@d6e32c1796099e0f1f3ac741c220a8b7eae9e5dd # v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build
        run: bun run build

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        working-directory:
          - .
          - templates/bun-npm-package
          - templates/slidev
    defaults:
      run:
        working-directory: ${{ matrix.working-directory }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup Bun and Node.js
        uses: jdx/mise-action@d6e32c1796099e0f1f3ac741c220a8b7eae9e5dd # v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Test
        run: bun run test
